#!/usr/bin/env bash
#by necro
clear
e="\e[0m"
re="\e[48;2;216;62;65m"
or="\e[48;2;232;115;38m"
yl="\e[48;2;225;224;58m"
gr="\e[48;2;0;166;102m"
bl="\e[48;2;20;102;176m"
pu="\e[48;2;85;91;167m"
bk="\e[38;05;232m" #black font
wh="\e[38;05;255m" #white font
while true; do
	d=$((RANDOM%6+1))
	echo -e "${wh}Dado de 6 lados. \nSeu valor é: $d$e\n"
	if [ "$d" == 1 ]; then
		echo -e "$re         $e"
		echo -e "$re         $e"
		echo -e "$re$bk    ●    $e"
		echo -e "$re         $e"
		echo -e "$re         $e\n"
	fi
	if [ "$d" == 2 ]; then
		echo -e "$or         $e"
		echo -e "$or$bk    ●    $e"
		echo -e "$or         $e"
		echo -e "$or$bk    ●    $e"
		echo -e "$or         $e\n"
	fi
	if [ "$d" == 3 ]; then
		echo -e "$yl$bk       ● $e"
		echo -e "$yl         $e"
		echo -e "$yl$bk    ●    $e"
		echo -e "$yl         $e"
		echo -e "$yl$bk ●       $e\n"
	fi
	if [ "$d" == 4 ]; then
		echo -e "$gr$bk ●     ● $e"
		echo -e "$gr         $e"
		echo -e "$gr         $e"
		echo -e "$gr         $e"
		echo -e "$gr$bk ●     ● $e\n"
	fi
	if [ "$d" == 5 ]; then
		echo -e "$bl$bk ●     ● $e"
		echo -e "$bl         $e"
		echo -e "$bl$bk    ●    $e"
		echo -e "$bl         $e"
		echo -e "$bl$bk ●     ● $e\n"
	fi
	if [ "$d" == 6 ]; then
		echo -e "$pu$bk ●     ● $e"
		echo -e "$pu         $e"
		echo -e "$pu$bk ●     ● $e"
		echo -e "$pu         $e"
		echo -e "$pu$bk ●     ● $e\n"
	fi
	echo -e "${wh}Rodar de novo? [enter/n] $e"; read -p "" input;
	case $input in
		"")
			echo -e "${wh}Limpando dados.$e"
			sleep 0.1
			clear
			;;
		[nN][oO]|[nN])
			echo -e "${wh}Nope. See you later!$e"
			break
			;;
	esac
done
exit
