#!/bin/bash
echo -e "Teste de ping... \n"

a=0

ping -c 3 www.youtube.com

until [ $? -eq 0 ];
	do
		echo -e "\nTestando de novo... \n"
		sleep 2
		echo -e "Numero de tentativas: "$a
		((a++))
		ping -c 3 www.youtube.com
	done
echo -e "\nInternet ok."
